# Site settings
title: r-statistics.co
email: rcodeprogramming@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A resource that makes statistical computing with R simple.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://r-statistics.co" # the base hostname & protocol for your site
twitter_username: r_programming
github_username:  selva86

# Build settings
markdown: kramdown
